spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/azure-demo-org/springapps-petclinic-microservices-config.git
        native:
          search-locations: classpath:.
  profiles:
    active: native
